# Generated by Django 2.0.3 on 2020-05-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('sport', models.CharField(max_length=64)),
                ('maxPlayers', models.IntegerField()),
            ],
        ),
    ]
