# Generated by Django 3.0.6 on 2020-05-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200520_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='main.UserProfile'),
        ),
    ]
