# Generated by Django 3.0.6 on 2020-05-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_match_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(null=True, to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='matches',
            field=models.ManyToManyField(null=True, to='main.Match'),
        ),
    ]
