# Generated by Django 3.0.6 on 2020-05-21 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200521_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='matches',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.Match'),
        ),
    ]
