# Generated by Django 3.0.6 on 2020-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200521_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='matches',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='players', to='main.Match'),
        ),
    ]
